import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

import { Toaster } from "react-hot-toast";
import { AppProvider } from "@/components/AppContext";
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Food Ordering App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
        <main className="max-w-5xl mx-auto p-4">
          <AppProvider>
            <Toaster />
            <Header />

            {children}
            <Footer />
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
